### ISSUE TITLE
Error running X-Net and ACE-Net for Texas dataset

### ISSUE THREAD

**Issue by TongfeiLiu** [llu025/Heterogeneous_CD#11]
Dear author,
hi! For the Texas dataset, X-Net and ACE-Net will debug each time when they train to 80/240, as shown in the figure. Could you help me with this problem? Thank you very much!

![error](https://user-images.githubusercontent.com/52185946/175305757-42cea6e5-6607-499f-84ad-529d204e91c3.png)

**Comment by llu025** [comment]
Hello! I would say the problem is that at epoch 80 and 160 the model obtains a first change detection, and uses the result as new alpha. However, it seems the training did not go as expected, and the output of the network, `x_hat` and `y_hat`, and consequently `d`, contain NaN. I would recommend check if that is the case by inspecting `x_hat` and `y_hat`, not necessarily at epoch 80, also earlier. Please let me know how things evolve!

**Comment by TongfeiLiu** [comment]
Dear Dr. Luigi Tommaso Luppino

Thank you very much for your reply. I carefully adjusted the test epoch, indeed, early in the model training (epoch=3; epoch=8; epoch 12; Epoch 24, etc.) X_hat and y_hat have collapsed into NaN. Also, we check that initial alpha is correct, but after training the crash results in X_hat and y_hat being NaN. At present, the problem has not been solved.

Thank you again for your help.

Tongfei Liu
Xidian University

________________________________
发件人: Luigi Tommaso Luppino ***@***.***>
发送时间: Monday, June 27, 2022 1:54:54 AM
收件人: llu025/Heterogeneous_CD ***@***.***>
抄送: Tongfei ***@***.***>; Author ***@***.***>
主题: Re: [llu025/Heterogeneous_CD] Error running X-Net and ACE-Net for Texas dataset (Issue #11)


Hello! I would say the problem is that at epoch 80 and 160 the model obtains a first change detection, and uses the result as new alpha. However, it seems the training did not go as expected, and the output of the network, x_hat and y_hat, and consequently d, contain NaN. I would recommend check if that is the case by inspecting x_hat and y_hat, not necessarily at epoch 80, also earlier. Please let me know how things evolve!

―

**Comment by llu025** [comment]
My recommendation is to try and put several breakpoints, one after each important line, such as a multiplication or division, network inference, heavy calculation etc. and see where the NaNs first appear. By the way, are you using the X-Net and ACE-net from the legacy folder or the new ones? Because the new code has not been fully tested. Please let me know, and feel free to add screenshots, terminal output, and whatever can help me help you :)

**Comment by TongfeiLiu** [comment]
Dear Dr. Luigi Tommaso Luppino

Thank you very much for your reply. I have resolved related issues. The reason for the above-mentioned BUG is that the change-prior generated for the first time is not conducive to subsequent detection. To adress this problem, the program can be run by trying to generate a new change-prior several times. I've got the detection result.  To thank you for your help, I will cite your works in my paper and acknowledge you. Thank you again.

Good luck with your work.

Tongfei Liu
Xidian University
***@***.***



发件人: Luigi Tommaso ***@***.***>
发送时间: 2022年7月7日 17:16
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [llu025/Heterogeneous_CD] Error running X-Net and ACE-Net for Texas dataset (Issue #11)


My recommendation is to try and put several breakpoints, one after each important line, such as a multiplication or division, network inference, heavy calculation etc. and see where the NaNs first appear. By the way, are you using the X-Net and ACE-net from the legacy folder or the new ones? Because the new code has not been fully tested. Please let me know, and feel free to add screenshots, terminal output, and whatever can help me help you :)

―
