### ISSUE TITLE
about the final_evaluate()

### ISSUE THREAD

**Issue by haoranwu22** [llu025/Heterogeneous_CD#13]
![image](https://user-images.githubusercontent.com/52814900/203326782-2c059fd5-a8a7-4452-aa29-f9973ec6ca51.png)
Dear Dr.Luppino,
When I am running `Code_Aligned_Autoencoders.py`, I find that after the final epoch, the 'ACC' obtained by `final_evaluate()` is much higher than that in the historical last epoch(such as the 'ACC' increases from 0.783 to 0.928 in this picture and I set 21 as the final epoch). Do you know the reason? It is strange.
Thank you!

**Comment by llu025** [comment]
The reason is simple: in the other epochs another function is used where a much simpler filter is applied to the difference image. This is because the dense CRF filtering method used in the final epoch is much more computationally expensive and therefore it would have slowed down the training.

I have to say, I did not try to change it and use the dense CRF method during all epochs. It might have a performance boost in terms of classification.
