### ISSUE TITLE
cGAN.py file in the Code-Aligned_Autoencoders project doesn't work properly

### ISSUE THREAD

**Issue by kamen-kkr** [llu025/Heterogeneous_CD#16]
Greetings! Thank you very much for your contribution to the various algorithms in the open source Heterogeneous_CD project! However, the cGAN.py file in the Code-Aligned_Autoencoders project does not run properly to obtain results.
For example, the California dataset was used as requested, and when the cGAN.py file is run, a dimensionality inconsistency occurs at the 12th epoch of training, as shown below: 
![image](https://github.com/llu025/Heterogeneous_CD/assets/116727984/8451e8f8-842e-4cc2-83b0-dd74664699d4)
The same situation occurs when using multiple other datasets.
I would like to express my thanks again and hope to get your reply and answer!😀

**Comment by llu025** [comment]
Hello,

from the screenshot you sent me I cannot really understand much of what is going on. However, I noticed that the error happens at epoch 12. This means that at epoch 11 the `if` statement at [this line](https://github.com/llu025/Heterogeneous_CD/blob/ef0784fba5ee26653e02f8b8f92683518c628b60/Code-Aligned_Autoencoders/cGAN.py#L243) was triggered and the calculation of a new `Pu` is computed. This is clearly leading to a wrong result, since `Pu` has a wrong shape at epoch 12 and raises the error printed in your screenshot.

Can you provide more information? For example, can you check what is the dimensionality of `Pu` after it is computed at epoch 11?

**Comment by llu025** [comment]
Hello @kamen-kkr, did you finally manage to work things out? If this issue will stay inactive for another 2 months, I will close it.

**Comment by kamen-kkr** [comment]
Yes, I've solved this problem. I am very sorry that I did not reply in time after solving the problem, thank you for your attention!



At 2024-02-27 19:31:01, "Luigi Tommaso Luppino" ***@***.***> wrote:

Hello @kamen-kkr, did you finally manage to work things out? If this issue will stay inactive for another 2 months, I will close it.
