### ISSUE TITLE
about the file change-prior.mat

### ISSUE THREAD

**Issue by aiyeshi** [llu025/Heterogeneous_CD#3]
Dear Dr.Luppino,
When I ran the X-net.py for the Texas dataset, an error occurred: FileNotFoundError: [Errno 2] No such file or directory: 'data/Texas/change-prior.mat'. Could you provide me with change-prior.mat? And how to construct the mat file?
Thank you very much!
Aiye

**Comment by llu025** [comment]
Hello,

The method looks for the .mat file in the specified folder but, in case this file is not existing, it should call the function evaluating (and storing) the prior (around line 500 of `X-net.py`):

```
           try:
                if PRE_TRAIN:
                    raise Exception("Forcing prior computation")
                self.Alpha = np.squeeze(scipy.io.loadmat(prior_path)[prior_name])
            except Exception as exc:
                print(exc)
                print("Prior under evaluation")
                self.Alpha = self.pre_train()
                self.save_image(255.0 * self.Alpha, "alpha.png")
                scipy.io.savemat(prior_path, {prior_name: self.Alpha})
```

Can you be more specific and explain when this issue arises?

**Comment by aiyeshi** [comment]
Dear Dr.Luppino,
Thank you very much!  When I ran  the file X-net.py at epoch 33, an error occurred. I wondered whether the change-prior.mat was not correct. Thus, I opened the file change-prior.mat in matlab software, I found there were many Nan values in the file change-prior.mat.  Could you tell me how to avoid the Nan value in the change-prior.mat?

**Comment by llu025** [comment]
The NaN values can be due to many different reasons, I cannot really say without looking at the data in hand. Also, why epoch 33? Did you change the number of epochs to 100? My guess is that the evaluation of the prior was problematic and created many NaNs, which then spoiled the training and brought to translated images full of NaNs themselves. Can you please check the prior computation? So the pre_training step.
