### ISSUE TITLE
how to process more channels images and where I can ouput the full size change map

### ISSUE THREAD

**Issue by Yusin2Chen** [llu025/Heterogeneous_CD#5]
Hi Dr.Luppino,

Thank you for sharing so nice work and code. I am doing similar work and want to compare it with your results. But unfortunately, I am not familiar with TensorFlow.  When I try to use your code to process images with more than three channels, there always have a problem in "**tmp2 = tf.concat** Line 76 of decorators.py". Could you give me help with parameter setting?  and I try to get the whole resolution change map from here " change_map = self._change_map(difference_img)"  line 248 of change_dtector.py. But the image I got is very small, I don't know how to do it. Hope you can give me some tips~

Best regards,
yusin

**Comment by llu025** [comment]
Concerning the image reduction, I believe what is happening is that your dataset is reduced in the function `fetch()` in `dataset.py` (line 342) because you do not have a GPU running with CUDA:

```
if not tf.config.list_physical_devices("GPU"):
        dataset = [
            tf.image.central_crop(tensor, 0.1) for tensor in [x_im, y_im, target_cm]
        ]
    else:
        dataset = [x_im, y_im, target_cm]
```

If you want to avoid this, you can simply replace "0.1" with "1" and the function would behave exactly as if these lines were not there.
Please notice that the same "if" statement affects also the parameter setting in `config.py`, so you would have to change line 22 with `if not debug:`.

About the images with more channels, the method is supposed to handle any kind of number of channels (except 2, I have to fix it). In `config.py` there is a selection of channels to be printed out ("channel_x" and "channel_y") in case there are more than 3. In conclusion, I struggle to understand your question. Can you provide more details about the error, sharing for example what python prints out?

**Comment by Yusin2Chen** [comment]
Hi Dr.Luppino,

Thank you very much for your help. It works~

Best regards,
yusin
