### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by yyaoshuai** [llu025/Heterogeneous_CD#8]
Dear Dr.Luppino
Regarding the steps of code running, can there be a more detailed description

**Comment by llu025** [comment]
Hello,

I am not entirely sure I understood the question, can you be more specific? Do you mean the training steps? Or simply how to run the code?

**Comment by yyaoshuai** [comment]
I want to talk about the steps of training

Luigi Tommaso Luppino ***@***.***> 于2021年6月25日周五 下午10:42写道：

**Comment by llu025** [comment]
During each training epoch, several batches of random patches are extracted from co-located regions of the images X and Y and  fed to the network and the optimiser minimises the objective function.
At the end of each epoch, the entire images X and Y are fed to the network and the resulting translated images are used to perform change detection, whose output is compared to the ground truth for quantitative evaluation.
At every 50 epochs, a prior is computed and used to aid the code alignment.

Please refer to the original paper for further details, please find the link in the home page of this repository.
I am not sure I cleared your doubts, please let me know if you have other questions otherwise close the issue. Thank you!
